// Generated by CoffeeScript 1.3.3
(function() {
  var ObjectId, Schema, obj, services;

  services = require('mongoose');

  Schema = services.Schema;

  ObjectId = Schema.ObjectId;

  obj = {
    id: ObjectId,
    username: {
      type: String,
      set: toLower,
      validate: [validator, '最小位数 >= 5; 最大位数 <= 10']
    },
    alias: String,
    password: {
      type: String,
      validate: [validator, '最小位数 >= 5; 最大位数 <= 10']
    },
    email: String,
    role: {
      type: String,
      "default": 'admin'
    },
    cdate: {
      type: Date,
      "default": Date.now
    },
    mdate: {
      type: Date,
      "default": Date.now
    }
  };

  exports.AdminsSchema = new Schema(obj);

  exports.obj2json = function(obj) {
    var json;
    return json = {
      id: obj.id,
      username: obj.username,
      alias: obj.alias,
      password: obj.password,
      email: obj.email,
      role: obj.role,
      cdate: obj.cdate,
      mdate: obj.mdate
    };
  };

  
/**
 * to lower
 */
function toLower ( value ) {
  return value.toLowerCase();
}

/**
 * validator 5 >= x <= 10
 */
function validator ( value ) {
  return value.length >= 5 && value.length <= 10;
}
;


}).call(this);
