// Generated by CoffeeScript 1.3.3
(function() {
  var ObjectId, Schema, obj, services;

  services = require('mongoose');

  Schema = services.Schema;

  ObjectId = Schema.ObjectId;

  obj = {
    id: ObjectId,
    catename: String,
    alias: String,
    cdate: {
      type: Date,
      "default": Date.now
    },
    mdate: {
      type: Date,
      "default": Date.now
    }
  };

  exports.CategoriesSchema = new Schema(obj);

}).call(this);
