// Generated by CoffeeScript 1.3.3
(function() {
  var ObjectId, Schema, obj, services;

  services = require('mongoose');

  Schema = services.Schema;

  ObjectId = Schema.ObjectId;

  obj = {
    id: ObjectId,
    modelname: String,
    currentid: {
      type: Number,
      "default": 1
    }
  };

  exports.IdGeneratorSchema = new Schema(obj);

}).call(this);
