// Generated by CoffeeScript 1.3.3
(function() {
  var MongoStore, app, config, express, mongo, router, services;

  express = require('express');

  services = require('./server/business/services');

  router = require('./server/router/router');

  config = require('./server/business/config');

  mongo = config.mongo;

  MongoStore = require('connect-mongo')(express);

  app = module.exports = express.createServer();

  app.configure = function() {
    app.set('views', __dirname + '/client/views');
    app.set('view engine', 'html');
    app.register('.html', require('ejs'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express["static"](__dirname + '/client/public'));
    app.use(express.cookieParser('asgard-cookie'));
    app.use(express.session({
      secret: 'asgard-session-secret',
      cookie: {
        maxAge: 2 * 24 * 60 * 60 * 1000
      },
      store: new MongoStore({
        url: config.get_monog_url(mongo)
      })
    }));
    app.use(app.router);
    return app.set('view options', {
      layout: false
    });
  };

  app.configure('development', function() {
    return app.use(express.errorHandler({
      showStack: true,
      dumpExceptions: true
    }));
  });

  app.configure('production', function() {});

  router(app);

  app.listen(config.port);

  console.log("Server start at http://" + config.host + ":" + config.port);

  services.once('services_connected_success', function(result) {
    return console.log('services connected');
  });

  services.once('services_connected_error', function(error) {
    return console.log("error = " + error);
  });

  services.connect(config.get_monog_url(mongo));

}).call(this);
