// Generated by CoffeeScript 1.3.3
(function() {
  var db, events, exports;

  db = require('mongoose');

  events = require('events');

  exports = module.exports = new events.EventEmitter();

  exports.connect = function(url) {
    try {
      console.log('mongodb url = ' + url);
      db.connect(url);
      return exports.emit('services_connected_success', 'success');
    } catch (error) {
      console.log("mongodb connect error" + error);
      return exports.emit('services_connected_error', error);
    }
  };

}).call(this);
