// Generated by CoffeeScript 1.3.3
(function() {
  var AdminsModel, admins_model, setMember;

  admins_model = require('../model/admins-model');

  AdminsModel = admins_model.AdminsModel;

  exports.setup = function(req, res) {
    var random;
    random = require('../libs/random').random;
    admins_model.once(random + '_admins_findall_success', function(result) {
      if (result != '') {
        return res.redirect('/');
      } else {
        return res.render('back-end/setup');
      }
    });
    admins_model.once(random + '_admins_findall_error', function(err) {
      return console.log('_admins_findall_error = ' + err);
    });
    return admins_model.findAll(AdminsModel, random);
  };

  exports.add = function(req, res) {
    var obj, random;
    console.log('req.body.username   = ' + req.body.username);
    console.log('req.body.password   = ' + req.body.password);
    console.log('req.body.alias      = ' + req.body.alias);
    console.log('req.body.email      = ' + req.body.email);
    console.log('req.body.role       = ' + req.body.role);
    obj = new AdminsModel();
    obj.username = req.body.username;
    obj.password = req.body.password;
    obj.alias = req.body.alias;
    obj.email = req.body.email;
    obj.role = req.body.role;
    random = require('../libs/random').random;
    admins_model.once(random + '_admins_add_success', function(result) {
      return res.redirect('/asgard-signin');
    });
    admins_model.once(random + '_admins_add_error', function(err) {
      return console.log('_admins_add_error = ' + err);
    });
    return admins_model.add(obj, random);
  };

  exports.profile = function(req, res) {
    var random, updates;
    console.log('req.body.username   = ' + req.body.username);
    console.log('req.body.password   = ' + req.body.password);
    console.log('req.body.alias      = ' + req.body.alias);
    console.log('req.body.email      = ' + req.body.email);
    console.log('req.body.role       = ' + req.body.role);
    random = require('../libs/random').random;
    updates = {
      username: req.body.username,
      password: req.body.password,
      alias: req.body.alias,
      email: req.body.email,
      role: req.body.role,
      mdate: new Date()
    };
    admins_model.once(random + '_admins_save_success', function(result) {
      console.log('_admins_save_success =' + result);
      return res.redirect('/admin-profile');
    });
    admins_model.once(random + '_admins_save_error', function(err) {
      return console.log('_admins_save_error = ' + err);
    });
    return admins_model.save(AdminsModel, req.body.username, updates, random);
  };

  exports.updateprofile = function(req, res) {
    var member, random;
    member = setMember(req, res);
    console.log('member.username = ' + member.username);
    random = require('../libs/random').random;
    admins_model.once(random + '_admins_findusername_success', function(result) {
      console.log('_admins_findusername_success =' + result);
      if (req.session.member != null) {
        req.session.member = JSON.stringify(result);
      }
      res.cookie('member', JSON.stringify(result));
      return res.redirect('/dashboard');
    });
    admins_model.once(random + '_admins_findusername_error', function(err) {
      return console.log('_admins_findusername_error = ' + err);
    });
    return admins_model.findUsername(AdminsModel, member.username, random);
  };

  setMember = function(req, res) {
    var member;
    member = req.session.member ? req.session.member : req.cookies.member;
    return member = JSON.parse(member);
  };

}).call(this);
