// Generated by CoffeeScript 1.3.3
(function() {
  var ContentsModel, category, contents_model, getCategoiesHandler, getOperatorsHandler, getpagination, operator, page, pageno, pagesize, pagination, pv, setMember, total;

  pagination = require('node-pagination');

  contents_model = require('../model/contents-model');

  ContentsModel = contents_model.ContentsModel;

  operator = require('./operator');

  category = require('./category');

  pageno = 1;

  pagesize = 10;

  pv = {};

  total = 1;

  exports.init = function(req, res) {
    var member, query, random;
    pageno = 1;
    member = setMember(req, res);
    random = require('../libs/random').random;
    contents_model.once(random + '_contents_count_success', function(result) {
      total = result;
      if (result != null && result > 0) {
        pv = getpagination();
      }
      return page(req, res);
    });
    contents_model.once(random + '_contents_count_error', function(err) {
      return console.log('_contents_count_error = ' + err);
    });
    query = member.role === 'admin' ? {} : {
      'username': member.username
    };
    return contents_model.count(ContentsModel, query, random);
  };

  exports.page = page = function(req, res) {
    var member, query, random;
    pageno = req.params.page != undefined ? req.params.page : 1;
    member = setMember(req, res);
    random = require('../libs/random').random;
    pv = getpagination();
    contents_model.once(random + '_contents_findall_success', function(result) {
      if (req.xhr) {
        return res.render('back-end/content-table', {
          contents: result,
          pv: pv
        });
      } else {
        if (member.role === 'admin') {
          return operator.getoperators(req, res, result, pv, getOperatorsHandler);
        } else {
          return res.render('back-end/dashboard', {
            member: member,
            contents: result,
            pv: pv
          });
        }
      }
    });
    contents_model.once(random + '_contents_findall_error', function(err) {
      return console.log('_contents_findall_error = ' + err);
    });
    query = member.role === 'admin' ? {} : {
      'username': member.username
    };
    return contents_model.findAll(ContentsModel, query, pageno, pagesize, random);
  };

  getOperatorsHandler = function(req, res, obj) {
    return category.getcategoies(req, res, obj, getCategoiesHandler);
  };

  getCategoiesHandler = function(req, res, obj, result) {
    var member;
    member = setMember(req, res);
    return res.render('back-end/dashboard', {
      member: member,
      contents: obj.contents,
      pv: obj.pv,
      operators: obj.operators,
      categories: result
    });
  };

  getpagination = function() {
    return pagination.build(total, pageno, pagesize, 0, pagesize);
  };

  setMember = function(req, res) {
    var member;
    member = req.session.member ? req.session.member : req.cookies.member;
    return member = JSON.parse(member);
  };

}).call(this);
